module core

import os

// The fixtures are real output from a live Linux host, with addresses moved to
// the RFC 5737 documentation range and MACs to the RFC 7042 documentation MAC.
// Structure, spacing and field order are untouched, because those are what the
// parsers actually depend on.
//
// testdata/resolvectl_status.sample is the exception and says so where it is
// used: systemd-resolved was not running on the development machine, so that
// one is written from the documented output format rather than captured.
fn sample(name string) !string {
	return os.read_file(os.join_path(@VMODROOT, 'testdata', name))!
}

// ── resolv.conf ──────────────────────────────────────────────────────────────
fn test_parse_resolv_conf_reads_nameservers_in_order() ! {
	text := sample('resolv_conf_stub.sample')!
	servers := parse_resolv_conf(text)

	assert servers == ['127.0.0.53']
}

fn test_parse_resolv_conf_ignores_comments_and_other_directives() {
	text := '# Generated by NetworkManager\n' + '; a semicolon comment\n' + 'search lan\n' + 'options edns0 trust-ad\n' + 'nameserver 192.0.2.1\n' + 'nameserver 198.51.100.1\n' + 'nameserver\n'
	servers := parse_resolv_conf(text)

	// The bare "nameserver" line has no address and contributes nothing.
	assert servers == ['192.0.2.1', '198.51.100.1']
}

fn test_parse_resolv_conf_of_an_empty_file() {
	assert parse_resolv_conf('') == []string{}
}

// ── default route ────────────────────────────────────────────────────────────
fn test_parse_default_route_prefers_the_lowest_metric() ! {
	// The fixture has two default routes: a laptop on wifi with a second
	// adapter attached. Taking the first line would name wlp3s0's competitor
	// in every output line for the rest of the run.
	text := sample('ip_route.sample')!
	gateway, ifname := parse_default_route(text)

	assert gateway == '192.0.2.1'
	assert ifname == 'wlp3s0'
}

fn test_parse_default_route_treats_a_missing_metric_as_zero() {
	// A route written without a metric has metric 0 in the kernel, which is
	// higher priority than any explicit one.
	text := 'default via 198.51.100.1 dev eth1 proto static metric 100 \n' + 'default via 192.0.2.1 dev eth0 proto dhcp \n'
	gateway, ifname := parse_default_route(text)

	assert gateway == '192.0.2.1'
	assert ifname == 'eth0'
}

fn test_parse_default_route_with_no_default_route() {
	text := '172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown \n'
	gateway, ifname := parse_default_route(text)

	assert gateway == ''
	assert ifname == ''
}

// ── tunnel detection ─────────────────────────────────────────────────────────
fn test_parse_tunnel_interfaces_finds_a_tunnel_that_is_up() ! {
	// The fixture host has Tailscale running. docker0 and enp4s0 also carry UP
	// in their flags and are not tunnels; wlp3s0 is up and is the real link.
	text := sample('ip_link.sample')!
	tunnels := parse_tunnel_interfaces(text)

	assert tunnels == ['tailscale0']
}

fn test_tunnel_detection_reads_flags_not_state() {
	// tailscale0 reports "state UNKNOWN" while carrying traffic. A check keyed
	// on "state UP" misses every WireGuard and Tailscale interface there is,
	// which is the whole population this warning exists for.
	line := '4: tailscale0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 500\\    link/none '

	assert line.contains('state UNKNOWN')
	assert parse_tunnel_interfaces(line) == ['tailscale0']
}

fn test_tunnel_that_is_down_is_not_reported() {
	line := '7: wg0: <POINTOPOINT,NOARP> mtu 1420 qdisc noop state DOWN mode DEFAULT group default qlen 1000\\    link/none '

	assert parse_tunnel_interfaces(line) == []string{}
}

fn test_tunnel_name_drops_its_parent_interface() {
	line := '8: tun0@eth0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 500\\    link/none '

	assert parse_tunnel_interfaces(line) == ['tun0']
}

fn test_a_host_with_no_tunnels_reports_none() {
	line := '3: wlp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DORMANT group default qlen 1000\\    link/ether 00:00:5e:00:53:01 brd 00:00:5e:00:53:01'

	assert parse_tunnel_interfaces(line) == []string{}
}

// ── resolvectl ───────────────────────────────────────────────────────────────
fn test_parse_resolvectl_status_collects_upstreams() ! {
	// Fixture written from systemd-resolved's documented output, not captured:
	// see the note at the top of this file and on parse_resolvectl_status.
	text := sample('resolvectl_status.sample')!
	upstreams := parse_resolvectl_status(text)

	// "Current DNS Server" and "DNS Servers" overlap; the address appears once.
	// The zone survives: fe80::1 without it is a different address, and one that
	// would leave via whatever interface the kernel happened to pick.
	assert upstreams == ['192.0.2.1', 'fe80::1%wlp3s0']
}

fn test_a_point_to_point_default_route_still_names_its_interface() {
	// OpenVPN and some WireGuard setups install "default dev tun0" with no
	// gateway. Requiring a via would let the higher-metric wifi route win and
	// file a tunnelled run under wlan0, which is exactly the mix-up that
	// stamping ifname into every line exists to prevent.
	text := 'default via 192.0.2.1 dev wlan0 proto dhcp metric 600 \n' + 'default dev tun0 scope link metric 50 \n'
	gateway, ifname := parse_default_route(text)

	assert ifname == 'tun0'
	assert gateway == ''
}

fn test_parse_resolvectl_status_when_resolved_is_not_running() {
	// What this machine actually prints. detect() turns a non-zero exit into an
	// empty string, so the parser only ever sees this if the command succeeded
	// and said nothing useful.
	assert parse_resolvectl_status('') == []string{}
}

// ── cache classification ─────────────────────────────────────────────────────
fn test_loopback_resolvers_are_marked_as_caches() {
	// 127.0.0.53 is the systemd-resolved stub, 127.0.0.1 a local dnscrypt-proxy
	// or unbound. Both answer from memory, and comparing memory against a
	// network round trip is the error GRC's v1 made and its v2 fixed.
	assert is_loopback('127.0.0.53')
	assert is_loopback('127.0.0.1')
	assert is_loopback('127.53.0.1')
	assert is_loopback('::1')

	assert !is_loopback('192.0.2.1')
	assert !is_loopback('1.1.1.1')
	assert !is_loopback('2606:4700:4700::1111')
}

// ── detect ───────────────────────────────────────────────────────────────────
fn test_detect_never_fails_on_this_machine() {
	// detect() has no error return by design: every step degrades to nothing.
	// This asserts the contract holds rather than asserting values, which
	// depend on whatever network the test happens to run on.
	info := detect()

	for r in info.resolvers {
		assert r.ip != ''
		assert r.is_cache == is_loopback(r.ip)
	}
	if info.gateway != '' {
		assert info.ifname != ''
	}
	assert info.vpn_detected() == (info.tunnels.len > 0)
}

fn test_the_same_parser_reads_an_ipv6_default_route() {
	// `ip -6 route` prints default routes in the same shape, so IPv6 presence
	// needs no parser of its own.
	text := 'default via fe80::aec7:f1ff:fe84:fd1e dev wlp3s0 proto ra metric 600 pref medium\n' + 'default via fe80::aec7:f1ff:fe84:fd1e dev wlp14s0f3u3 proto ra metric 601 pref medium\n'
	gateway, ifname := parse_default_route(text)

	assert gateway == 'fe80::aec7:f1ff:fe84:fd1e'
	assert ifname == 'wlp3s0'
}

fn test_a_link_without_ipv6_reports_no_default_route() {
	gateway, _ := parse_default_route('')
	assert gateway == ''
}
